[project]
name = "qf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dylan" }
]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.4.6",
    "pandas>=3.0.6",
    "scipy>=1.17.1",
]

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
